plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.112'
}

version = project.mod_version
group = project.mod_group
base { archivesName = 'Applied-Industrialization' }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
    withSourcesJar()
}

repositories {
    mavenLocal()
    maven { url "https://maven.aliyun.com/repository/public/" }
    maven { url "https://maven.aliyun.com/repository/google/" }
    maven { url "https://repo.huaweicloud.com/repository/maven/" }
    maven { url "https://mirrors.cloud.tencent.com/nexus/repository/maven-public/" }
    maven {
        url "https://www.cursemaven.com"
    }
    maven {
        url "https://spongepowered.org/maven/"
    }
    maven {
        url "https://modmaven.dev/mekanism/Mekanism/"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    flatDir {
        dir 'libs'
    }
    mavenCentral()
}

neoForge {
    version = project.neoforge_version
    parchment {
        minecraftVersion = '1.21'
        mappingsVersion = '2024.07.28'
    }
    mods {
        aeind { sourceSet sourceSets.main }
    }
    runs {
        configureEach {
            gameDirectory = project.file('run')
            systemProperty 'forge.logging.console.level', 'debug'
            loadedMods = [mods.aeind]
        }
        client { client() }
        server { server() }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
        }
    }
}

dependencies {
    compileOnly files('libs/appliedenergistics2-19.2.17.jar')
    compileOnly files('libs/Modern-Industrialization-2.5.6.jar')
    compileOnly files('libs/Jade-1.21.1-NeoForge-15.10.6.jar')
    compileOnly files('libs/tesseract-api-neoforge-1.12.13-1.21.1.jar')
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }

processResources {
    def props = [version: project.mod_version, mod_id: project.mod_id, mod_name: project.mod_name, neo_version: project.neoforge_version, neo_version_range: project.neoforge_version_range]
    inputs.properties props
    filesMatching('META-INF/neoforge.mods.toml') { expand props }
}
